### ISSUE TITLE
[Errno 2] No such file or directory: 'logs/trevi_final_masked_flipxzinitenv/train_images.json'

### ISSUE THREAD

**Issue by stillbetter** [r00tman/NeRF-OSR#8]
Hi @r00tman ,
Thanks for sharing the code and the wonderful work.
I 've downloaded all the models and data. But when I try to run the tesh *sh scripts, there is an error message like:

> Traceback (most recent call last):
  File "/home/mi/anaconda3/envs/nerf/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/mi/PycharmProjects/NeRF-OSR/ddp_test_nerf.py", line 48, in ddp_test_nerf
    start, models = create_nerf(rank, args)
  File "/home/mi/PycharmProjects/NeRF-OSR/ddp_train_nerf.py", line 348, in create_nerf
    with open(f) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/trevi_final_masked_flipxzinitenv/train_images.json'

I want to know how can I  get these json file or how to generate them?

**Comment by debangsha-versatile** [comment]
I have the same problem

**Comment by debangsha-versatile** [comment]
So it turns out you get the file when you run `ddp_train_nerf.py`

**Comment by BenyunZhao** [comment]
where can i find the envmap ?
